speicfy_range = [1,3:14,16:17,21:23,25:32,34,37];

section_label = ones(200,1,10);
section_feature = ones(200,size(speicfy_range, 2),10);

train_feature = experiment_feature(1:2000,speicfy_range);
train_label = experiment_label(1:2000,:);
test_feature = experiment_feature(2401:3000,speicfy_range);
test_label = experiment_label(2401:3000,:);

for i=1:10
    section_label(:,:,i) = train_label((200*(i-1)+1):(200*i),:);
    section_feature(:,:,i) = train_feature((200*(i-1)+1):(200*i),:);
end

accuracy_10_folder = ones(10, 1);
train_feature_10 = ones(1800,size(speicfy_range, 2),10);
train_label_10 = ones(1800, 1, 10);


train_label_10(:,:,1) = [section_label(:,:,2);section_label(:,:,3);section_label(:,:,4);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,1) = [section_feature(:,:,2);section_feature(:,:,3);section_feature(:,:,4);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,2) = [section_label(:,:,1);section_label(:,:,3);section_label(:,:,4);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,2) = [section_feature(:,:,1);section_feature(:,:,3);section_feature(:,:,4);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,3) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,4);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,3) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,4);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,4) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,4) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,5) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,5) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,6) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,6) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,7) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,7) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];


train_label_10(:,:,8) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,7);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,8) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,7);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,9) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,7);section_label(:,:,8);section_label(:,:,10)];


train_feature_10(:,:,9) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,7);section_feature(:,:,8);section_feature(:,:,10)];

train_label_10(:,:,10) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,7);section_label(:,:,8);section_label(:,:,9)];


train_feature_10(:,:,10) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,7);section_feature(:,:,8);section_feature(:,:,9)];


for j = 1:10

    model_post = svmtrain(train_label_10(:,:,j), train_feature_10(:,:,j), '-c 1 -g 0.07');
    [predict_label, accuracy_10_folder_temp, prob_est] = svmpredict(section_label(:,:,j), ...
            section_feature(:,:,j), model_post);
        
    %cMatrix = confusionmat(test_label_10, predict_label);
    %confusion_matrix_plot();

    accuracy_10_folder(j) = accuracy_10_folder_temp(1);
end


