section_label = ones(210,1,10);
section_feature = ones(210,size(speicfy_range, 2),10);

CV_cell_label = train_label(1:700,:);
CV_cell_inst = train_feature(1:700,:);

CV_debris_label = train_label(701:1400,:);
CV_debris_inst = train_feature(701:1400,:);

CV_strip_label = train_label(1401:2100,:);
CV_strip_inst = train_feature(1401:2100,:);

for i=1:10
    sub_part = [(70*(i-1)+1):(70*i)];
    section_label(:,:,i) = [CV_cell_label(sub_part);CV_debris_label(sub_part);CV_strip_label(sub_part)];
    section_feature(:,:,i) = [CV_cell_inst(sub_part,:);CV_debris_inst(sub_part,:);CV_strip_inst(sub_part,:)];
end

accuracy_10_folder = ones(10, 1);
train_feature_10 = ones(1890,size(speicfy_range, 2),10);
train_label_10 = ones(1890, 1, 10);


train_label_10(:,:,1) = [section_label(:,:,2);section_label(:,:,3);section_label(:,:,4);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,1) = [section_feature(:,:,2);section_feature(:,:,3);section_feature(:,:,4);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,2) = [section_label(:,:,1);section_label(:,:,3);section_label(:,:,4);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,2) = [section_feature(:,:,1);section_feature(:,:,3);section_feature(:,:,4);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,3) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,4);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,3) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,4);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,4) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,5);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,4) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,5);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,5) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,6);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,5) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,6);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,6) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,7);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,6) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,7);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,7) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,8);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,7) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,8);section_feature(:,:,9);section_feature(:,:,10)];


train_label_10(:,:,8) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,7);section_label(:,:,9);section_label(:,:,10)];


train_feature_10(:,:,8) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,7);section_feature(:,:,9);section_feature(:,:,10)];

train_label_10(:,:,9) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,7);section_label(:,:,8);section_label(:,:,10)];


train_feature_10(:,:,9) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,7);section_feature(:,:,8);section_feature(:,:,10)];

train_label_10(:,:,10) = [section_label(:,:,1);section_label(:,:,2);section_label(:,:,3);...
    section_label(:,:,4);section_label(:,:,5);section_label(:,:,6);...
    section_label(:,:,7);section_label(:,:,8);section_label(:,:,9)];


train_feature_10(:,:,10) = [section_feature(:,:,1);section_feature(:,:,2);section_feature(:,:,3);...
    section_feature(:,:,4);section_feature(:,:,5);section_feature(:,:,6);...
    section_feature(:,:,7);section_feature(:,:,8);section_feature(:,:,9)];


for j = 1:10

    model_post = svmtrain(train_label_10(:,:,j), train_feature_10(:,:,j), '-c 2 -g 4');
    [predict_label, accuracy_10_folder_temp, prob_est] = svmpredict(section_label(:,:,j), ...
            section_feature(:,:,j), model_post);
        
    %cMatrix = ConfusionMatrix(section_label(:,:,j), predict_label);
    %confusion_matrix_plot;

    accuracy_10_folder(j) = accuracy_10_folder_temp(1);
end

accuracy_ave_10CV = sum(accuracy_10_folder)/10;


